### ISSUE TITLE
Error: find() timed out.

### ISSUE THREAD

**Issue by StuFull** [apexad/eufy-robovac#16] opened 2021-01-24 18:18 UTC
Hi,

I get this persistent error which appears to prevent any other plugins from displaying their accessories in Hoobs.

24/01/2021, 17:24:51 Error: find() timed out. Is the device powered on and the ID or IP correct?
24/01/2021, 17:24:51 at /home/hoobs/.hoobs/node_modules/tuyapi/index.js:622:13
24/01/2021, 17:24:51 at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/p-timeout/index.js:25:13)
24/01/2021, 17:24:51 at listOnTimeout (internal/timers.js:554:17)
24/01/2021, 17:24:51 at processTimers (internal/timers.js:497:7)

System details -

Hoobs 3.3.2
Node 14.15.1
Eufy Robovac 2.1.1

Device Eufy 30C Max 
Device WiFi 1.1.5
Device MCU 1.2.1

DevId & LocalKey are confirmed correct.

**Comment by Raptor0014** [comment] 2021-01-25 19:17
I also get this error. I enabled the debug log and this is what I am getting tonight.

25/01/2021, 19:14:23 Error: find() timed out. Is the device powered on and the ID or IP correct?
25/01/2021, 19:14:23 at /home/hoobs/.hoobs/node_modules/tuyapi/index.js:622:13
25/01/2021, 19:14:23 at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/p-timeout/index.js:25:13)
25/01/2021, 19:14:23 at listOnTimeout (internal/timers.js:549:17)
25/01/2021, 19:14:23 at processTimers (internal/timers.js:492:7)
25/01/2021, 19:14:23 Connecting...
25/01/2021, 19:14:23 Disconnected!
25/01/2021, 19:14:23 Robovac Error {}
25/01/2021, 19:14:23 Error: find() timed out. Is the device powered on and the ID or IP correct?
25/01/2021, 19:14:23 at /home/hoobs/.hoobs/node_modules/tuyapi/index.js:622:13
25/01/2021, 19:14:23 at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/p-timeout/index.js:25:13)
25/01/2021, 19:14:23 at listOnTimeout (internal/timers.js:549:17)
25/01/2021, 19:14:23 at processTimers (internal/timers.js:492:7)
25/01/2021, 19:14:23 Connecting...
25/01/2021, 19:14:23 Robovac Error {}
25/01/2021, 19:14:23 Disconnected!
25/01/2021, 19:14:24 Connected!
25/01/2021, 19:14:24 Robovac Error {}
25/01/2021, 19:14:24 Disconnected!
25/01/2021, 19:14:32 Connected!
25/01/2021, 19:14:32 Robovac Error {}
25/01/2021, 19:14:32 Disconnected!
25/01/2021, 19:14:49 Robovac Error {}
25/01/2021, 19:14:49 Robovac Error {}
25/01/2021, 19:14:49 Robovac Error {}
25/01/2021, 19:14:49 Disconnected!
25/01/2021, 19:14:49 Disconnected!
25/01/2021, 19:14:49 Disconnected!
25/01/2021, 19:15:07 Robovac Error {}
25/01/2021, 19:15:07 Disconnected!

The only way to solve is to delete the plugin and re add. It then works for a few hours and then borks again.

As above my system details -

Hoobs 3.3.2
Node 14.15.1
Eufy Robovac 2.1.1

Device Eufy 30C Max
Device WiFi 1.1.5
Device MCU 1.2.1

DevId & LocalKey are confirmed correct.

**Comment by HunterDG** [comment] 2021-01-31 02:17
+1

Homebridge 1.2.5 on Mac
Node 13.11.0
Eufy Robovac 2.1.1

Device: Eufy 30C
Device WiFi 1.1.5
Device MCU 1.1.7

deleting and re-adding plugin doesn't help for me

devId & localKey are confirmed correct

**Comment by jlxq0** [comment] 2021-02-03 12:29
+1

**Comment by joneian** [comment] 2021-02-07 22:50
Same here.

Node v12.15.0
Device: Eufy 30C

devId & localKey checked from logcat output.

**Comment by apexad** [comment] 2021-02-10 11:24
duplicate of https://github.com/apexad/homebridge-eufy-robovac/issues/30
Track there.
I'm hoping to finally get a chance to work on this soon, but no specific ETA

**Closed by apexad** 2021-02-10 11:24 UTC
