### ISSUE TITLE
Device not recognized at Step 4

### ISSUE THREAD

**Issue by ceomitch** [apexad/eufy-robovac#24] opened 2021-11-02 02:17 UTC
I've tried everything. I just need personal help at this point. Thanks in advance.

**Comment by apexad** [comment] 2022-02-11 16:15
Likely a local key/device id issue. So duplicate of https://github.com/apexad/eufy-robovac/issues/14 which I plan to work on soon.

**Closed by apexad** 2022-02-11 16:15 UTC
